server:
  port: 8080

spring:
  application:
    name: ApiGateWayApplication

  # --- AI Model Configurations ---
  ai:
    openai:
      base-url: https://api.groq.com/openai
      api-key: ${GROQ_API_KEY:}
      chat:
        options:
          model: llama-3.1-8b-instant

    google:
      genai:
        api-key: ${GEMINI_API_KEY:}
        chat:
          options:
            model: gemini-2.5-flash

  # --- Redis (For Rate Limiting ) ---
  data:
    redis:
      host: localhost
      port: 6379
      password:
      connect-timeout: 2000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  sql:
    init:
      mode: always

  datasource:
    url: jdbc:mysql://localhost:3306/api_gateway_db
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver

# --- Security () ---
jwt:
  secret: MySuperSecretEnterpriseKeyThatIsVeryLongAndSecure123!
  expirationMs: 3600000